SELECT
	A.*
	INTO #MESES
	FROM(
		SELECT 2015 [CODMES]
		UNION ALL
		SELECT 2016 [CODMES]
		UNION ALL
		SELECT 2017 [CODMES]
		UNION ALL
		SELECT 2018 [CODMES]
		UNION ALL
		SELECT 2019 [CODMES]
	) A

DECLARE @COLSPIVOT NVARCHAR(MAX)

SET @COLSPIVOT = 
	STUFF(
		(SELECT 
			CASE 
				WHEN ROW_NUMBER() OVER (ORDER BY M.CODMES) = 1 THEN QUOTENAME(M.CODMES)
				ELSE ',' + QUOTENAME(M.CODMES)
			END
		FROM (SELECT DISTINCT CODMES FROM #MESES) M
		FOR XML PATH('') )
		,1 
		,1
		,'')

PRINT @COLSPIVOT