
SELECT 
	PO.ID,
	PO.NAME,
	PO.GENDER,
	PO.SALARY,
	TB.AVGSALARY,
	TB.MINSALARY,
	TB.MAXSALARY
	FROM PERSONAS_OVER PO
INNER JOIN (
	SELECT 
		GENDER
		,COUNT(SALARY) [GENDERTOTAL]
		,AVG(SALARY) [AVGSALARY]
		,MIN(SALARY) [MINSALARY]
		,MAX(SALARY) [MAXSALARY]
		FROM PERSONAS_OVER
	GROUP BY 
		GENDER
		) AS TB ON TB.GENDER = PO.GENDER;

/* LO MISMO PERO CON OVER
*/

SELECT 
	ID
	,NAME
	,GENDER
	,SALARY
	,COUNT(SALARY) OVER ( PARTITION BY GENDER ) AS COUNTGENDER
	,AVG(SALARY) OVER ( PARTITION BY GENDER ) AS AVGSALARYBYGENDER
	,MIN(SALARY) OVER ( PARTITION BY GENDER ) AS MINSALARYBYGENDER
	,MAX(SALARY) OVER ( PARTITION BY GENDER ) AS MAXSALARYBYGENDER
	FROM PERSONAS_OVER