GO

SELECT
	A.*
	INTO #COURSESALES
	FROM(
		SELECT '.NET' [COURSE], 2012 [YEAR], 10000.00 [EARNING]
		UNION ALL
		SELECT 'Java' [COURSE], 2012 [YEAR], 20000.00 [EARNING]
		UNION ALL
		SELECT '.NET' [COURSE], 2012 [YEAR], 5000.00 [EARNING]
		UNION ALL
		SELECT '.NET' [COURSE], 2013 [YEAR], 48000.00 [EARNING]
		UNION ALL
		SELECT 'Java' [COURSE], 2013 [YEAR], 30000.00 [EARNING]
	) A

GO

SELECT * FROM #COURSESALES

GO

SELECT * FROM #COURSESALES
PIVOT(
SUM(EARNING) FOR COURSE IN ([.NET], [Java])
)
AS PIVOTTABLE;

SELECT * FROM #COURSESALES
PIVOT(
SUM(EARNING) FOR YEAR IN ([2012], [2013], [2014])
) AS PVT



GO

SELECT
	A.*
	INTO #FAMILIA
	FROM(
		SELECT '1/01/2017' [FECHA], 'Mamá' [COMPRADOR], 'Combustible' [TIPO], 74 [IMPORTE]
		UNION ALL
		SELECT '15/01/2017' [FECHA], 'Mamá' [COMPRADOR], 'Comida' [TIPO], 235 [IMPORTE]
		UNION ALL
		SELECT '17/01/2017' [FECHA], 'Papá' [COMPRADOR], 'Deportes' [TIPO], 20 [IMPORTE]
		UNION ALL
		SELECT '21/01/2017' [FECHA], 'Julia' [COMPRADOR], 'Libros' [TIPO], 125 [IMPORTE]
		UNION ALL
		SELECT '2/02/2017' [FECHA], 'Mamá' [COMPRADOR], 'Comida' [TIPO], 235 [IMPORTE]
		UNION ALL
		SELECT '20/02/2017' [FECHA], 'Julia' [COMPRADOR], 'Música' [TIPO], 20 [IMPORTE]
		UNION ALL
		SELECT '25/02/2017' [FECHA], 'Julia' [COMPRADOR], 'Entradas' [TIPO], 125 [IMPORTE]
	) A

SELECT * FROM #FAMILIA


SELECT 
	PVT.TIPO,
	SUM(ISNULL(PVT.Julia, 0)) [Julia],
	SUM(ISNULL(PVT.Mamá,0)) [Mamá],
	SUM(ISNULL(PVT.Papá,0)) [Papá],
	SUM(ISNULL(PVT.Julia,0) + ISNULL(PVT.Mamá,0) + ISNULL(PVT.Papá,0)) [TOTAL GENERAL]
 FROM #FAMILIA
PIVOT
(
	SUM(IMPORTE) FOR COMPRADOR IN ([Julia],[Mamá],[Papá])
)
AS PVT
GROUP BY PVT.TIPO
ORDER BY PVT.TIPO



